version: "2.2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo       
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"